[package]
name = "rustlib"
version = "0.1.0"
edition = "2018"
authors = ["Jonas Schröder <jonas.schroeder@posteo.de>"]

[lib]
name = "rustlib"
crate-type = ["cdylib"]

[dependencies]
cpython = {version = "0.2", features = ["extension-module"]}
